/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baiguixeoop.UI;

import baiguixe.DTO.hoadonDTO;
import baiguixe.DTO.veThangDTO;
import baiguixe.Service.SystemService;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class thongkexe extends javax.swing.JFrame {
      SystemService ss;
      DefaultTableModel tb=new DefaultTableModel();
      
    /**
     * Creates new form frame1
     */
    public thongkexe() {
        initComponents();
        setLocationRelativeTo(null);
        ss=new SystemService();
        tungay.setDate(java.sql.Date.valueOf(LocalDate.now()));
        denngay.setDate(java.sql.Date.valueOf(LocalDate.now()));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String var1=sdf.format(tungay.getDate());
        String var2=sdf.format(denngay.getDate());
        ArrayList<hoadonDTO> hd=ss.hienthihoadon(var1, var2);
        hienThiBang(hd);
        int luotxe=ss.thongkeLuotGui(var1, var2);
        tongluot.setText(String.valueOf(luotxe));
        int tienxe=ss.TongThu(var1, var2);
        tongtien.setText(String.valueOf(tienxe));
        
    }
    public void hienThiBang(ArrayList<hoadonDTO> hds){
         tb.setColumnIdentifiers(new String[]{"Biển số xe","Loại xe","Giờ vào","Giờ ra","Mã số vé","Loại vé","Thành tiền"});
         bangxe.setModel(tb);
         DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
         //ArrayList<hoadonDTO> ves =ss.thongkeVeThang(tungay, denngay);
        for(hoadonDTO hd:hds ) {
         tb.addRow(new Object[]{hd.getBienSoXeOut(),hd.getLoaiXeOut(),hd.getGioVaoXeOut().format(formatter),hd.getTimeOut().format(formatter),hd.getVeXeOut(),hd.getLoaiVeXeOut(),hd.getThanhTien()});
        }
         
    }
    public void ChuyenDoi(){
          for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }
          //tongluot.setText(" ");
          //tongtien.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tracuu = new javax.swing.JButton();
        chonxe = new javax.swing.JComboBox<>();
        tungay = new com.toedter.calendar.JDateChooser();
        denngay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangxe = new javax.swing.JTable();
        lammoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tongluot = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tongtien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vetrangchu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("                        THỐNG KÊ LƯỢT GỬI XE");

        jLabel4.setText("Đến Ngày :");

        jLabel5.setText("Từ Ngày :");

        tracuu.setText("Tra Cứu");
        tracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracuuActionPerformed(evt);
            }
        });

        chonxe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tổng Xe", "Ô tô", "Xe máy" }));
        chonxe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chonxeitemStateChange(evt);
            }
        });
        chonxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonxeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(chonxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tungay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denngay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(tracuu)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tracuu)
                .addComponent(chonxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(denngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bangxe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Biển Số Xe", "Loại Xe", "Loại Vé", "Mã Vé", "Vị Trí", "Ngày Nhận", "Giờ Nhận", "Ngày Trả", "Giờ Trả", "Số Tiền"
            }
        ));
        jScrollPane1.setViewportView(bangxe);

        lammoi.setText("Làm mới");
        lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiActionPerformed(evt);
            }
        });

        jLabel2.setText("Tổng số lượt :");

        tongluot.setEditable(false);

        jLabel6.setText("Tổng số tiền :");

        tongtien.setEditable(false);
        tongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongtienActionPerformed(evt);
            }
        });

        jLabel7.setText("Lượt");

        jLabel8.setText("VND");

        vetrangchu.setText("Quay lại");
        vetrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vetrangchuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vetrangchu)
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tongluot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vetrangchu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tongluot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chonxeActionPerformed

    private void tongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tongtienActionPerformed

    private void chonxeitemStateChange(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chonxeitemStateChange
        // TODO add your handling code here:
        chonxe = (JComboBox<String>) evt.getSource();
        if (evt.getStateChange() == ItemEvent.SELECTED){
            
            if (chonxe.getSelectedItem().toString().equals("Tổng Xe")){
                ChuyenDoi();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String var1=sdf.format(tungay.getDate());
                String var2=sdf.format(denngay.getDate());
                ArrayList<hoadonDTO> hd1=ss.hienthihoadon(var1, var2);
                hienThiBang(hd1);
                int luotxe=ss.thongkeLuotGui(var1, var2);
                tongluot.setText(String.valueOf(luotxe));
                int tienxe=ss.TongThu(var1, var2);
                tongtien.setText(String.valueOf(tienxe));
              
            } else {
                ChuyenDoi();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String var1=sdf.format(tungay.getDate());
                String var2=sdf.format(denngay.getDate());
                ArrayList<hoadonDTO> hd=ss.hienthiphanloai(var1, var2,chonxe.getSelectedItem().toString());
                hienThiBang(hd);
                int luotxe=ss.thongkePhanLoai(var1, var2,chonxe.getSelectedItem().toString());
                tongluot.setText(String.valueOf(luotxe));
                int tienxe=ss.TongThuPhanLoai(var1, var2, chonxe.getSelectedItem().toString());
                tongtien.setText(String.valueOf(tienxe));
                
            }
           
        } 
    }//GEN-LAST:event_chonxeitemStateChange

    private void tracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracuuActionPerformed
        // TODO add your handling code here:
        if (chonxe.getSelectedItem().toString().equals("Tổng Xe")){
                ChuyenDoi();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String var1=sdf.format(tungay.getDate());
                String var2=sdf.format(denngay.getDate());
                ArrayList<hoadonDTO> hd=ss.hienthihoadon(var1, var2);
                hienThiBang(hd);
                int luotxe=ss.thongkeLuotGui(var1, var2);
                tongluot.setText(String.valueOf(luotxe));
                int tienxe=ss.TongThu(var1, var2);
                tongtien.setText(String.valueOf(tienxe));
              
            } else {
                ChuyenDoi();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String var1=sdf.format(tungay.getDate());
                String var2=sdf.format(denngay.getDate());
                ArrayList<hoadonDTO> hd=ss.hienthiphanloai(var1, var2,chonxe.getSelectedItem().toString());
                hienThiBang(hd);
                int luotxe=ss.thongkePhanLoai(var1, var2,chonxe.getSelectedItem().toString());
                tongluot.setText(String.valueOf(luotxe));
                int tienxe=ss.TongThuPhanLoai(var1, var2, chonxe.getSelectedItem().toString());
                tongtien.setText(String.valueOf(tienxe));
                
            }
    }//GEN-LAST:event_tracuuActionPerformed

    private void lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiActionPerformed
        // TODO add your handling code here:
        ChuyenDoi();
        tungay.setDate(java.sql.Date.valueOf(LocalDate.now()));
        denngay.setDate(java.sql.Date.valueOf(LocalDate.now()));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String var1=sdf.format(tungay.getDate());
        String var2=sdf.format(denngay.getDate());
        ArrayList<hoadonDTO> hd=ss.hienthihoadon(var1, var2);
        hienThiBang(hd);
        int luotxe=ss.thongkeLuotGui(var1, var2);
        tongluot.setText(String.valueOf(luotxe));
        int tienxe=ss.TongThu(var1, var2);
        tongtien.setText(String.valueOf(tienxe));
        chonxe.setSelectedIndex(0);
        
    }//GEN-LAST:event_lammoiActionPerformed

    private void vetrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vetrangchuActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vetrangchuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thongkexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thongkexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thongkexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thongkexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thongkexe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangxe;
    private javax.swing.JComboBox<String> chonxe;
    private com.toedter.calendar.JDateChooser denngay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lammoi;
    private javax.swing.JTextField tongluot;
    private javax.swing.JTextField tongtien;
    private javax.swing.JButton tracuu;
    private com.toedter.calendar.JDateChooser tungay;
    private javax.swing.JButton vetrangchu;
    // End of variables declaration//GEN-END:variables
}
